apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  .Release.Name  }}iot-sensor
  labels:
    app: iot-sensor
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: iot-sensor
  template:
    metadata:
      labels:
        app: iot-sensor
        release: prometheus
    spec:
      containers:
      - name: dummy-sensor
        #image: akhsan/iot-dummy:v2
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{  .Values.image.pullPolicy  }}
        ports:
          - name: metrics
            containerPort: 8080
            protocol: TCP