{
 "title": "Sensor Dummy IoT",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "sensor",
    "label": "Pilih Ruangan/Sensor",
    "query": {
     "query": "label_values(iot_temperature_celsius,sensor_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Suhu Real-time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iot_temperature_celsius{sensor_id=~\"$sensor\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Kelembaban Real-time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iot_humidity_percent{sensor_id=~\"$sensor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Baterai Real-time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iot_battery_level_percent{sensor_id=~\"$sensor\"}",
     "legendFormat": "{{pods}}"
    }
   ]
  },
  {
   "title": "Sinyal WiFi Realtime",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iot_signal_strength_dbm{sensor_id=~\"$sensor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Data ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iot_total_readings{sensor_id=~\"$sensor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Suhu (History).",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "iot_temperature_celsius{sensor_id=~\"$sensor\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Grafik Battery (History)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "iot_battery_level_percent{sensor_id=~\"$sensor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Kelembaban (History)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "iot_humidity_percent{sensor_id=~\"$sensor\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Grafik Sinyal WiFi (History)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "iot_signal_strength_dbm{sensor_id=~\"$sensor\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}