replicaCount: 1

image:
  repository: registry.akhsanpasha.my.id/ujicoba/iot-dummy
  tag: "a00c920"
  pullPolicy: Always
  imagePullSecrets:
  - name: regcred

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: "10m"
    memory: "10Mi"
  limits:
    cpu: "50m"
    memory: "50Mi"