replicaCount: 1

image:
  repository: registry.akhsanpasha.my.id/ujicoba/iot-dummy
  tag: "e617603"
  pullPolicy: Always
  imagePullSecrets:
    - name: regcred

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

env:
  SENSOR_INTERVAL: "30"
  SENSOR_COUNT: "5"
  ERROR_RATE: "0.05"

probes:
  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 10
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 5

metrics:
  enabled: true
  path: /metrics
  port: 8080

dashboard:
  enabled: true