name: Build and Push to Private Registry

on:
  push:
    branches:
      - main
      - 'fix/**'
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  ci-process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Dapatkan Git Short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      # Install Emulator QEMU untuk arsitektur ARM
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Build Docker Image (Local)
        run: docker build -t iot-dummy:latest ./backend
      
      - name: Login ke Private Registry
        # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker login ${{ secrets.REGISTRY_LINK }} -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWORD }}

      - name: Tag & Push Docker Image ke Registry
        # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          IMAGE_PATH="registry.akhsanpasha.my.id/ujicoba/iot-dummy"
          TAG="${{ steps.vars.outputs.sha_short }}"
          
          docker tag iot-dummy:latest $IMAGE_PATH:$TAG
          docker push $IMAGE_PATH:$TAG

      - name: Update Helm values.yaml (GitOps Style)
        run: |          
          sed -i "s/^  tag: .*/  tag: ${{ steps.vars.outputs.sha_short }}/g" iot-chart/values.yaml          
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      
      # - name: Build and Push
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./backend
      #     platforms: linux/amd64, linux/arm64
      #     push: true
      #     tags: ${{ secrets.DOCKER_USERNAME }}/iot-dummy:latest,${{ secrets.DOCKER_USERNAME }}/iot-dummy:v7