name: Build and Push to Private Registry

on:
  push:
    branches:
      - main
      - 'fix/**'
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'iot-chart/values.yaml' # Cegah infinite loop

permissions:
  contents: write

jobs:
  ci-cd-process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Dapatkan Git Short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      # Install Emulator QEMU untuk arsitektur ARM
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Build Docker Image (Local)
        run: docker build -t iot-dummy:latest ./backend
      
      - name: Run Trivy Vulnerability Scanner
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:0.50.1 image \
            --exit-code 1 \
            --severity CRITICAL,HIGH \
            iot-dummy:latest
      
      - name: Login ke Private Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker login ${{ secrets.REGISTRY_LINK }} -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWORD }}

      - name: Tag & Push Docker Image ke Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          IMAGE_PATH="registry.akhsanpasha.my.id/ujicoba/iot-dummy"
          TAG="${{ steps.vars.outputs.sha_short }}"
          
          docker tag iot-dummy:latest $IMAGE_PATH:$TAG
          docker push $IMAGE_PATH:$TAG
      
      - name: Update Helm values.yaml & Push
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |              
          # Ubah tag di values.yaml
          sed -i "s/^  tag: .*/  tag: ${{ steps.vars.outputs.sha_short }}/g" iot-chart/values.yaml 
          
          # Konfigurasi Git Bot
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          if ! git diff-index --quiet HEAD; then
            git commit -m "chore: update image tag to ${{ steps.vars.outputs.sha_short }} [skip ci]"
            git push origin main
          else
            echo "Tidak ada perubahan di values.yaml"
          fi